version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:15.0.2
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: <username>
      KEYCLOAK_PASSWORD: <password>
    volumes:
      - ./realm-export.json:/tmp/realm-export.json
      - keycloak_data:/opt/jboss/keycloak/standalone/data/realm-export

  react-app:
    build:
      context: ./frontend  
      dockerfile: Dockerfile.react  
    ports:
      - "3000:3000"

volumes:
  keycloak_data:
